---
- hosts: '{{target}}'
  vars_files:
    - deploy-vars.yml
  gather_facts: false
  user: nestegg

  tasks:
    - name: Create project directory
      file: state=directory path={{ project_root }}
      tags:
        - provision

    - name: Update project directory
      file: group={{ project_user }} owner={{ project_user }} mode=755 state=directory path={{ project_root }}
      tags:
        - provision

    - name: Create /var/www directory
      file: state=directory path=/var/www
      become: true
      tags:
        - provision

    - name: Setup symlink
      file: src={{ project_root }} dest=/var/www/{{ project_name }} state=link
      become: true
      when: node_env == "staging"
      tags:
        - provision

    - name: Setup symlink for site
      file: src={{ project_root }} dest=/var/www/nesteggguru.com state=link
      become: true
      when: node_env == "production"
      tags:
        - provision

    - name: Setup symlink for blog
      file: src={{ project_root }} dest=/var/www/blog.nesteggguru.com state=link
      become: true
      when: node_env =="production"
      tags:
        - provision

    - name: Setup symlink
      file: src={{ project_root }} dest=/var/www/{{ project_name }} state=link
      become: true
      tags:
        - provision

    - name: Install nginx config file
      copy: src=files/{{ node_env }}/nesteggguru dest=/etc/nginx/sites-available/{{ project_name }}
      become: true
      become_user: root
      when: load_balanced == "false"
      notify: restart nginx
      tags:
        - provision

    - name: Install nginx config file
      copy: src=files/production-load-balanced/nesteggguru.nginx dest=/etc/nginx/sites-available/{{ project_name }}
      become: true
      become_user: root
      when: load_balanced == "true" and node_env == "production"
      notify: restart nginx
      tags:
        - provision

    - name: Setup nginx symlink
      file: src=/etc/nginx/sites-available/{{ project_name }} dest=/etc/nginx/sites-enabled/{{ project_name }} state=link
      notify: restart nginx
      become: true
      become_user: root
      tags:
        - provision

    - name: Setup init script
      copy: src=files/{{ node_env }}/nesteggguru.init dest=/etc/init.d/{{ project_name }} mode=0751
      become: true
      become_user: root
      when: load_balanced == "false"
      tags:
        - provision

    - name: Setup init script
      copy: src=files/production-load-balanced/nesteggguru.init dest=/etc/init.d/{{ project_name }} mode=0751
      become: true
      become_user: root
      when: load_balanced == "true" and node_env == "production"
      tags:
        - provision

    - name: "Pull master from repository"
      git: repo={{ project_repo }} dest={{ project_root }} version={{ deployment_branch }} recursive=yes track_submodules=no force=yes
      tags:
        - deploy

    - name: "Set node environment"
      shell: "echo $NODE_ENV"
      environment:
        NODE_ENV: "{{ node_env }}"

    - name: Install NPM modules
      npm: path={{ project_root }} production=yes ignore_scripts=yes
      tags:
        - deploy

    # - name: Run migrations
    #   command: "{{item}}"
    #   args:
    #     chdir: "{{ project_root }}"
    #   environment:
    #     NODE_ENV: "{{node_env}}"
    #   with_items:
    #     - ./node_modules/.bin/sequelize db:migrate
    #   tags:
    #     - migrate

    - name: Restart server
      command: /bin/true
      notify: restart nestegg

  handlers:
    - include: handlers/handlers.yml